// <auto-generated />
namespace FinalDatLong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fsfs3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fsfs3));
        
        string IMigrationMetadata.Id
        {
            get { return "202311280839261_fsfs3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
